version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: erp_database
    environment:
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'app'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3309:3306'
    volumes:
      - ../app-database:/var/lib/mysql
    networks:
      - my-network
networks:
  my-network:


