server:
  port : 8082
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mysql://localhost:3309/app}
    username: ${DATABASE_USERNAME:app}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    properties:
      hibernate:
        show_sql: ${SHOW_SQL:true}

  security:
    jwt:
      secret: ${JWT_SECRET:bWFyY29zcmliZWlyb2Rlc291c2E=}
      refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:100}
      token-expiration: ${JWT_TOKEN_EXPIRATION:5}
  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: ${MAX_PAGE_SIZE:50}

  user:
    admin:
      email: ${EMAIL:admin@gmail.com}
      password: ${PASSWORD:123456}