server:
  port : 8082
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/erp_db}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
    sql-script-encoding: UTF-8
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        show_sql: ${SHOW_SQL:true}
  security:
    jwt:
      secret: ${JWT_SECRET:bWFyY29zcmliZWlyb2Rlc291c2E=}
      refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:100}
      token-expiration: ${JWT_TOKEN_EXPIRATION:15}
  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: ${MAX_PAGE_SIZE:50}

  user:
    admin:
      email: ${EMAIL:admin@gmail.com}
      password: ${PASSWORD:123456}