server:
  port : 8082
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mysql://localhost:3309/app}
    username: ${DATABASE_USERNAME:app}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    properties:
      hibernate:
        show_sql: ${SHOW_SQL:true}

  security:
    jwt:
      secret: ${JWT_SECRET:bWFyY29zcmliZWlyb2Rlc291c2E=}
      refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:10}
      token-expiration: ${JWT_TOKEN_EXPIRATION:3}